name: AdvancedHints CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0

    - uses: actions/checkout@v2.3.1

    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile References.zip
        Expand-Archive -Path References.zip -DestinationPath References

    - name: Restore project
      run: dotnet restore -p:Configuration=Release

    - name: Build project
      shell: pwsh
      run: |
        if ('${{ GITHUB.REF }}' -Match 'dev$') {
           dotnet build -p:DeployToServer=false -p:Configuration=Release -p:BuildNumber=${{ GITHUB.RUN_NUMBER }}
        } else {
           dotnet build -p:DeployToServer=false -p:Configuration=Release
        }
      env:
        EXILED_REFERENCES: ${{ github.workspace }}/References

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Results
        path: AdvancedHints/bin/Release
